package service;
import exceptions.AccountClosedException;
import exceptions.AccountNotFoundException;
import exceptions.InsufficientBalanceException;
import exceptions.InvalidAmountException;
import model.Account;
import model.Customer;
import dao.*;
import model.Transaction;
import receipts.ReceiptGenerator;
import util.DBUtil;

import java.io.IOException;
import java.lang.Math;
import java.sql.Connection;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;


public class BankService {
    private static CustomerDAO customerDAO = new CustomerDAO();
    private static AccountDAO accountDAO = new AccountDAO();
    private static TransactionDAO transactionDAO = new TransactionDAO();

    public void createAccount(String fname, String lname, String email, String phoneNumber, String address, long adharNumber, String panNumber) {
        // first, you have to create a customer object.
        Customer customer = new Customer(fname, lname, email, phoneNumber, address, panNumber, adharNumber);
        try {
            // then, you have to insert the details of this particular customer into the DBMS.    AND
            // then, get the customerID generated by the DBMS and use it to create a bank account in DBMS.
            int customerID = customerDAO.createCustomer(customer);
            if(customerID == -1) {
                System.out.println("Failed to create customer entry in DB.");
                return;
            }
            // now, create a bankaccount using this customerID.
            long accNumber = (long)(Math.random()* 10000000000000L);
            Account account = new Account(accNumber, customerID, "Savings", 0.0d, "Active", LocalDate.now());
            if(accountDAO.createBankAccount(account)){
                System.out.println("Bank Account created successfully.\nYour account number is : " + accNumber);
            } else {
                System.out.println("Failed to create account.");
            }

        } catch(SQLException e) {
            System.out.println("Error : " + e.getMessage());
        }
    }

    public void closeAccount(long accNumber) {
        try{
            // try to get the specified bank account object from DBMS first.
            Account account = accountDAO.getAccount(accNumber);
            // if it is not found, throw an AccountNotFoundException
            if(account == null){
                throw new AccountNotFoundException("Account not found in bank records.");
            }
            if(account.getStatus().equalsIgnoreCase("closed")) {
                throw new AccountClosedException("Account already closed. Unable to perform operation.");
            } else {
                if(accountDAO.closeBankAccount(accNumber)){
                    System.out.println("Bank account number " + accNumber + " closed successfully.");
                } else {
                    System.out.println("Failed to close bank account. Please try again.");
                }
            }

        } catch(AccountNotFoundException | AccountClosedException | SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

    public void withdraw(long accNumber, double amount) {
        try {
            if(amount < 0){
                throw new InvalidAmountException("Unable to initiate transaction due to negative value of amount.");
            }
            else if(amount == 0){
                throw new InvalidAmountException("Unable to initiate transaction due to amount = 0.");
            } else {
                Account acc = accountDAO.getAccount(accNumber);
                if(acc == null) {
                    throw new AccountNotFoundException("Invalid bank account number entered.");
                }
                if(acc.getStatus().equalsIgnoreCase("closed")) {
                    throw new AccountClosedException("Account already closed.");
                }

                // SAVINGS ACCOUNT : min_balance = 0
                // CURRENT ACCOUNT : min_balance = -1000
                double min_balance = acc.getAccountType().equalsIgnoreCase("savings") ? 0 : -1000;
                if(acc.getBankBalance() - amount < min_balance) {
                    throw new InsufficientBalanceException("Entered withdrawal amount exceeds the minimum balance rules of bank account.");
                }

                // first, set new balance in the account object.
                acc.setBankBalance(acc.getBankBalance() - amount);

                // then, update the bankAccount table in DBMS.
                if(accountDAO.updateAccount(acc)) {
                    // if the update is successful, then, create a new record in the transaction table  AND  generate a receipt.
                    Transaction t = new Transaction(acc.getAccNumber(), "Withdrawal", amount, LocalDateTime.now(), 0, "Withdrawal from account.");
                    transactionDAO.addTransaction(t);
                    // generate a receipt.
                    ReceiptGenerator.generateReceipt(t);
                    System.out.println("Withdrawal successful!");
                    System.out.println("Amount : ₹" + t.getAmount());
                    System.out.println("Transaction receipt generated.");

                } else {
                    // if the update is unsuccessful, then, print a message - FAILED TO WITHDRAW AMOUNT. PLEASE TRY AGAIN.
                    System.out.println("Error: Failed to update balance. Withdrawal operation unsuccessful.");
                }
            }

        } catch(InvalidAmountException | SQLException | AccountNotFoundException | AccountClosedException | InsufficientBalanceException |
                IOException e) {
            System.out.println("Error: " + e.getMessage());
        }

    }



    public void transfer(long accNumber, long recAccNumber, double amount) {
        try(Connection conn = DBUtil.getConnection()) {
            // get senders account
            Account senderAcc = accountDAO.getAccount(accNumber);
            if (senderAcc == null) {
                throw new AccountNotFoundException("Account does not exist at GG Bank.");
            }

            // bank account already exist. BUT. it's already closed.
            if (senderAcc.getStatus().equalsIgnoreCase("closed")) {
                throw new AccountClosedException("Account already closed.");
            }

            // get receivers account
            Account receiverAcc = accountDAO.getAccount(recAccNumber);
            if (receiverAcc == null) {
                throw new AccountNotFoundException("Account does not exist at GG Bank.");
            }

            // bank account already exist. BUT. it's already closed.
            if (receiverAcc.getStatus().equalsIgnoreCase("closed")) {
                throw new AccountClosedException("Account already closed.");
            }



            // check if specified withdrawal amount is less than the permitted limits.
            double overdraftLimit = 0;
            double currentAccountBalance = senderAcc.getBankBalance();

            if (senderAcc.getAccountType().equalsIgnoreCase("current")) {
                overdraftLimit = -5000;
            }

            if(currentAccountBalance - amount < overdraftLimit) {
                throw new InvalidAmountException("Withdrawal amount exceeds the permitted limits.\nCannot initiate transaction.");
            } else {
                try {
                    conn.setAutoCommit(false);
                    // deduct from senders account, create a transaction

                    // first update the property - balance - in the Account object.
                    senderAcc.setBankBalance(senderAcc.getBankBalance() - amount);

                    // call AccountDAO object to update the balance field in the DB by using the Account object.
                    boolean senderAccountUpdateState = accountDAO.transactionUpdateBalance(senderAcc, conn);

                    Transaction t1 = new Transaction(accNumber, "Transfer", amount, LocalDateTime.now(), recAccNumber, "Withdrawal from account for transfer");
                    transactionDAO.addTransferTransaction(t1, conn);

                    receiverAcc.setBankBalance(receiverAcc.getBankBalance() + amount);
                    boolean receiverAccountUpdateState = accountDAO.transactionUpdateBalance(receiverAcc, conn);
                    Transaction t2 = new Transaction(recAccNumber, "Transfer", amount, LocalDateTime.now(), accNumber, "Deposit to account via transfer");
                    transactionDAO.addTransferTransaction(t2, conn);


                    // receipt generation for transactions - t1 and t2
                    if (senderAccountUpdateState && receiverAccountUpdateState) {
                        ReceiptGenerator.generateReceipt(t1);
                        ReceiptGenerator.generateReceipt(t2);
                        conn.commit();
                        System.out.println("Transaction successful.\nAvailable balance: " + senderAcc.getBankBalance());
                    }

                } catch(SQLException e) {
                    conn.rollback();
                    System.out.println("Transaction failed: " + e.getMessage());
                    System.out.println("All operations rolled back.");
                }
            }
        } catch(InvalidAmountException | AccountNotFoundException | AccountClosedException | SQLException | IOException e) {
            System.out.println("Error: " + e.getMessage());
        }

    }

    public void getTransactionHistory(long accNumber){
        try {
            Account acc = accountDAO.getAccount(accNumber);
            if(acc == null) {
                throw new AccountNotFoundException("Invalid bank account number entered.");
            }
            if(acc.getStatus().equalsIgnoreCase("closed")) {
                throw new AccountClosedException("Account already closed.");
            }
            ArrayList<Transaction> allTransactions = transactionDAO.getAllTransactions(accNumber);
            if(allTransactions.isEmpty()){
                System.out.println("No transactions performed via this account.");
            } else {
                for(Transaction t : allTransactions) {
                    System.out.println("Transaction date    : " + t.getTimestamp());
                    System.out.println("Transaction type    : " + t.getTransactionType());
                    System.out.println("Amount              : " + t.getAmount());
                    System.out.println("Description         : " + t.getDescription());
                    System.out.println("=============================================");
                }
            }
        } catch(SQLException | AccountNotFoundException | AccountClosedException e) {
            System.out.println("Error: " + e.getMessage());
        }

    }



}
