package service;
import exceptions.AccountClosedException;
import exceptions.AccountNotFoundException;
import model.Account;
import model.Customer;
import dao.*;
import java.lang.Math;
import java.sql.SQLException;
import java.time.LocalDate;

public class BankService {
    private static CustomerDAO customerDAO = new CustomerDAO();
    private static AccountDAO accountDAO = new AccountDAO();
    private static TransactionDAO transactionDAO = new TransactionDAO();

    public void createAccount(String fname, String lname, String email, String phoneNumber, String address, long adharNumber, String panNumber) {
        // first, you have to create a customer object.
        Customer customer = new Customer(fname, lname, email, phoneNumber, address, panNumber, adharNumber);
        try {
            // then, you have to insert the details of this particular customer into the DBMS.    AND
            // then, get the customerID generated by the DBMS and use it to create a bank account in DBMS.
            int customerID = customerDAO.createCustomer(customer);
            if(customerID == -1) {
                System.out.println("Failed to create customer entry in DB.");
                return;
            }
            // now, create a bankaccount using this customerID.
            long accNumber = (long)(Math.random()* 10000000000000L);
            Account account = new Account(accNumber, customerID, "Savings", 0.0d, "Active", LocalDate.now());
            if(accountDAO.createBankAccount(account)){
                System.out.println("Bank Account created successfully.\nYour account number is : " + accNumber);
            } else {
                System.out.println("Failed to create account.");
            }

        } catch(SQLException e) {
            System.out.println("Error : " + e.getMessage());
        }
    }

    public void closeAccount(long accNumber) {
        try{
            // try to get the specified bank account object from DBMS first.
            Account account = accountDAO.getAccount(accNumber);
            // if it is not found, throw an AccountNotFoundException
            if(account == null){
                throw new AccountNotFoundException("Account not found in bank records.");
            }
            if(account.getStatus().equalsIgnoreCase("closed")) {
                throw new AccountClosedException("Account already closed. Unable to perform operation.");
            } else {
                if(accountDAO.closeBankAccount(accNumber)){
                    System.out.println("Bank account number " + accNumber + " closed successfully.");
                } else {
                    System.out.println("Failed to close bank account. Please try again.");
                }
            }



        } catch(AccountNotFoundException | AccountClosedException | SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

}
